# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChariotFall2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChariotFall2019
  pod 'AWSCore', '~> 2.10.0'
  pod 'AWSMobileClient', '~> 2.10.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.10.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.10.0'   # Optional dependency required to use drop-in UI
  
  pod  'AWSIoT', '~> 2.10.0'

  target 'ChariotFall2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChariotFall2019UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
